function daysAgo(days) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const WORK_ARRANGEMENT_LABELS = {
  onsite: 'Tại văn phòng',
  hybrid: 'Lai (Hybrid)',
  remote: 'Làm từ xa',
};

export const EXPERIENCE_LEVEL_LABELS = {
  Intern: 'Thực tập sinh',
  Entry: 'Mới đi làm',
  Junior: 'Junior',
  Mid: 'Mid-level',
  Senior: 'Senior',
};

export function formatPostedDate(dateStr) {
  if (!dateStr) return '';
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now - date;
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  if (diffDays <= 0) return 'Hôm nay';
  if (diffDays === 1) return 'Hôm qua';
  if (diffDays < 7) return `${diffDays} ngày trước`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} tuần trước`;
  return `${Math.floor(diffDays / 30)} tháng trước`;
}

// ── Demo / sample job data ──────────────────────────────────────────
// All entries below are synthetic sample data for demonstration purposes.
// source = "seed"  →  not scraped from any real job board.
export const SEED_JOBS = [
  {
    title: 'Data Analyst',
    company: 'MoMo (M_Service)',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'Data / Analytics',
    description:
      'Tham gia đội phân tích dữ liệu để xây dựng báo cáo, dashboard và cung cấp insight hỗ trợ ra quyết định kinh doanh. Làm việc với tập dữ liệu lớn từ sản phẩm ví điện tử.',
    requirements: [
      'Tốt nghiệp đại học ngành Toán thống kê, Khoa học máy tính, Kinh tế hoặc liên quan',
      'Thành thạo SQL và cơ sở dữ liệu quan hệ',
      'Có kinh nghiệm với Python hoặc R cho phân tích dữ liệu',
      'Thành thạo Excel và công cụ trực quan hóa (Power BI / Tableau)',
      'Tư duy phân tích, chú ý chi tiết',
    ],
    preferred_skills: ['Python', 'SQL', 'Excel', 'Power BI', 'Tableau', 'Statistics', 'Data Visualization', 'Pandas'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_001',
    posted_at: daysAgo(2),
    remote: false,
  },
  {
    title: 'Data Analyst Intern',
    company: 'FPT Corporation',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Data / Analytics',
    description:
      'Tham gia đội phân tích để làm việc với tập dữ liệu lớn, tạo báo cáo insight và hỗ trợ ra quyết định dựa trên dữ liệu. Bạn sẽ học hỏi từ các analyst kỳ cựu và đóng góp vào dự án thực tế.',
    requirements: [
      'Sinh viên năm 3-4 ngành Thống kê, Toán học, Khoa học máy tính, Kinh tế hoặc liên quan',
      'Kiến thức SQL và cơ sở dữ liệu quan hệ',
      'Thành thạo Microsoft Excel',
      'Hiểu biết cơ bản về phân tích dữ liệu và thống kê',
      'Chú ý chi tiết, kỹ năng giải quyết vấn đề',
    ],
    preferred_skills: ['Python', 'SQL', 'Excel', 'Data Analysis', 'Power BI', 'Tableau', 'Statistics', 'Data Visualization'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_002',
    posted_at: daysAgo(5),
    remote: false,
  },
  {
    title: 'Data Science Intern',
    company: 'VNG Corporation',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'hybrid',
    experience_level: 'Intern',
    field: 'Data / AI',
    description:
      'Làm việc với mô hình machine learning, pipeline dữ liệu và sản phẩm AI. Cộng tác cùng data scientist và engineer dày dặn kinh nghiệm trên bài toán thực tế.',
    requirements: [
      'Sinh viên năm 3-4 ngành Khoa học máy tính, Thống kê, Toán học hoặc liên quan',
      'Kiến thức lập trình Python',
      'Hiểu biết cơ bản về machine learning',
      'Quen thuộc với pandas, numpy, scikit-learn',
      'Tư duy phân tích mạnh',
    ],
    preferred_skills: ['Python', 'Machine Learning', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'SQL', 'Statistics', 'Data Visualization', 'Deep Learning'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_003',
    posted_at: daysAgo(8),
    remote: false,
  },
  {
    title: 'Business Analyst',
    company: 'Deloitte Vietnam',
    location: 'Hà Nội',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'Business / Consulting',
    description:
      'Hỗ trợ dự án tư vấn bằng cách phân tích quy trình kinh doanh, thu thập yêu cầu và lập báo cáo cho khách hàng đa ngành. Cơ hội phát triển nhanh trong môi trường tư vấn quốc tế.',
    requirements: [
      'Tốt nghiệp đại học ngành Kinh doanh, Kinh tế, Tài chính hoặc liên quan',
      'Kỹ năng phân tích và giải quyết vấn đề mạnh',
      'Thành thạo Excel và PowerPoint',
      'Kỹ năng giao tiếp xuất sắc, tiếng Anh tốt',
      'Khả năng làm việc nhóm',
    ],
    preferred_skills: ['Excel', 'PowerPoint', 'Data Analysis', 'Communication', 'Problem Solving', 'SQL', 'Financial Analysis', 'Market Research', 'Presentation'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_004',
    posted_at: daysAgo(3),
    remote: false,
  },
  {
    title: 'Business Analyst Intern',
    company: 'KPMG Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Business / Consulting',
    description:
      'Hỗ trợ đội tư vấn phân tích quy trình, thu thập yêu cầu và lập báo cáo cho khách hàng. Học hỏi phương pháp tư vấn chuẩn quốc tế trong môi trường Big 4.',
    requirements: [
      'Sinh viên năm 3-4 ngành Kinh doanh, Kinh tế, Tài chính hoặc liên quan',
      'Kỹ năng phân tích và giải quyết vấn đề',
      'Thành thạo Excel và PowerPoint',
      'Kỹ năng giao tiếp tốt, tiếng Anh khá',
      'Làm việc được trong môi trường nhóm',
    ],
    preferred_skills: ['Excel', 'PowerPoint', 'Data Analysis', 'Communication', 'Problem Solving', 'SQL', 'Financial Analysis', 'Market Research', 'Presentation'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_005',
    posted_at: daysAgo(10),
    remote: false,
  },
  {
    title: 'Software Engineer Intern',
    company: 'Tiki Corporation',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'hybrid',
    experience_level: 'Intern',
    field: 'IT / Software',
    description:
      'Tham gia đội engineering xây dựng và bảo trì ứng dụng web quy mô lớn. Làm việc với công nghệ hiện đại, học best practice từ senior engineer.',
    requirements: [
      'Sinh viên năm 3-4 ngành Khoa học máy tính, Kỹ thuật phần mềm hoặc liên quan',
      'Biết ít nhất một ngôn ngữ lập trình (Java, Python, JavaScript, C++)',
      'Hiểu biết cấu trúc dữ liệu và thuật toán',
      'Quen thuộc với khái niệm phát triển web',
      'Ham học hỏi, thích nghi nhanh',
    ],
    preferred_skills: ['Java', 'JavaScript', 'Python', 'React', 'Node.js', 'SQL', 'Git', 'HTML', 'CSS', 'REST API', 'Docker'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_006',
    posted_at: daysAgo(6),
    remote: false,
  },
  {
    title: 'Frontend Developer',
    company: 'Shopee Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'IT / Software',
    description:
      'Xây dựng giao diện người dùng cho nền tảng e-commerce quy mô lớn. Làm việc với React, tối ưu hiệu suất và trải nghiệm người dùng cho hàng triệu người dùng.',
    requirements: [
      'Tốt nghiệp đại học ngành Khoa học máy tính hoặc liên quan',
      'Thành thạo HTML, CSS, JavaScript/TypeScript',
      'Kinh nghiệm React hoặc Vue.js',
      'Hiểu biết về responsive design và accessibility',
      'Quen thuộc với Git, CI/CD',
    ],
    preferred_skills: ['JavaScript', 'TypeScript', 'React', 'HTML', 'CSS', 'Tailwind CSS', 'Git', 'REST API', 'Webpack', 'Jest'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_007',
    posted_at: daysAgo(1),
    remote: false,
  },
  {
    title: 'Backend Developer',
    company: 'Grab Vietnam',
    location: 'Hà Nội',
    job_type: 'Full-time',
    work_arrangement: 'remote',
    experience_level: 'Mid',
    field: 'IT / Software',
    description:
      'Thiết kế và phát triển các service backend quy mô lớn phục hàng triệu giao dịch mỗi ngày. Làm việc với microservices, hệ thống phân tán và cơ sở dữ liệu lớn.',
    requirements: [
      'Tốt nghiệp đại học ngành Khoa học máy tính hoặc liên quan',
      'Kinh nghiệm 3+ năm phát triển backend',
      'Thành thạo Go, Java hoặc Python',
      'Kinh nghiệm với microservices, REST/gRPC API',
      'Kiến thức về Redis, Kafka, PostgreSQL/MySQL',
    ],
    preferred_skills: ['Go', 'Java', 'Python', 'PostgreSQL', 'Redis', 'Kafka', 'Docker', 'Kubernetes', 'Microservices', 'REST API', 'gRPC'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_008',
    posted_at: daysAgo(4),
    remote: true,
  },
  {
    title: 'Full-stack Developer',
    company: 'Sapo Technology',
    location: 'Đà Nẵng',
    job_type: 'Full-time',
    work_arrangement: 'hybrid',
    experience_level: 'Junior',
    field: 'IT / Software',
    description:
      'Phát triển đầy đủ ngăn xếp cho nền tảng quản lý bán hàng. Tham gia từ thiết kế đến triển khai, làm việc với đội product để xây dựng tính năng mới.',
    requirements: [
      'Tốt nghiệp đại học ngành Khoa học máy tính hoặc liên quan',
      'Kinh nghiệm React/Next.js frontend',
      'Kinh nghiệm Node.js/Express backend',
      'Thành thạo SQL và NoSQL',
      'Hiểu biết về CI/CD, AWS/GCP',
    ],
    preferred_skills: ['JavaScript', 'React', 'Node.js', 'Next.js', 'PostgreSQL', 'MongoDB', 'Docker', 'AWS', 'REST API', 'GraphQL'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_009',
    posted_at: daysAgo(7),
    remote: false,
  },
  {
    title: 'Cybersecurity Intern',
    company: 'Bảo Việt Insurance',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'IT / Security',
    description:
      'Hỗ trợ đội an ninh mạng giám sát, phân tích và ứng phó sự cố bảo mật. Học hỏi về tiêu chuẩn bảo mật ngành tài chính và quy trình phản ứng sự cố.',
    requirements: [
      'Sinh viên năm 3-4 ngành An toàn thông tin, Khoa học máy tính hoặc liên quan',
      'Hiểu biết cơ bản về mạng và bảo mật',
      'Quen thuộc với Linux và công cụ bảo mật cơ bản',
      'Kỹ năng phân tích và giải quyết vấn đề',
      'Chú ý chi tiết',
    ],
    preferred_skills: ['Linux', 'Network Security', 'Python', 'Penetration Testing', 'SIEM', 'OWASP', 'Cryptography', 'Incident Response', 'Bash', 'Wireshark'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_010',
    posted_at: daysAgo(12),
    remote: false,
  },
  {
    title: 'Financial Analyst',
    company: 'Techcombank',
    location: 'Hà Nội',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'Finance / Banking',
    description:
      'Hỗ trợ đội phân tích tài chính trong nghiên cứu thị trường, mô hình tài chính và phân tích đầu tư. Rèn luyện kinh nghiệm thực tế trong ngành ngân hàng.',
    requirements: [
      'Tốt nghiệp đại học ngành Tài chính, Kinh tế, Kế toán hoặc liên quan',
      'Hiểu biết vững về báo cáo tài chính',
      'Thành thạo Excel',
      'Kiến thức thị trường tài chính',
      'Chú ý chi tiết, kỹ năng phân tích',
    ],
    preferred_skills: ['Excel', 'Financial Analysis', 'Financial Modeling', 'Accounting', 'Market Research', 'PowerPoint', 'SQL', 'Statistics', 'Valuation'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_011',
    posted_at: daysAgo(5),
    remote: false,
  },
  {
    title: 'Finance Intern',
    company: 'Vietcombank',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Finance / Banking',
    description:
      'Hỗ trợ phòng tài chính trong lập báo cáo, phân tích dữ liệu tài chính và quy trình vận hành. Cơ hội tiếp xúc thực tế với hoạt động ngân hàng thương mại.',
    requirements: [
      'Sinh viên năm 3-4 ngành Tài chính, Kế toán, Kinh tế hoặc liên quan',
      'Thành thạo Excel',
      'Hiểu biết cơ bản về kế toán',
      'Chú ý chi tiết, cẩn thận',
      'Kỹ năng giao tiếp tốt',
    ],
    preferred_skills: ['Excel', 'Accounting', 'Financial Analysis', 'Data Analysis', 'PowerPoint', 'Attention to Detail', 'Vietnamese Accounting Standards'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_012',
    posted_at: daysAgo(9),
    remote: false,
  },
  {
    title: 'Investment Banking Intern',
    company: 'SSI Securities',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Finance / Investment',
    description:
      'Hỗ trợ đội ngân hàng đầu tư trong nghiên cứu thị trường, lập mô hình tài chính và chuẩn bị tài liệu chào bán. Tiếp xúc thực tế với giao dịch M&A và IPO.',
    requirements: [
      'Sinh viên năm cuối ngành Tài chính, Kinh tế hoặc liên quan',
      'GPA từ 3.2/4.0 trở lên',
      'Thành thạo Excel và PowerPoint',
      'Kiến thức định giá và báo cáo tài chính',
      'Tiếng Anh lưu loát',
    ],
    preferred_skills: ['Excel', 'Financial Modeling', 'Valuation', 'PowerPoint', 'M&A', 'Financial Analysis', 'Market Research', 'Accounting', 'Statistics'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_013',
    posted_at: daysAgo(14),
    remote: false,
  },
  {
    title: 'Marketing Intern',
    company: 'Unilever Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'hybrid',
    experience_level: 'Intern',
    field: 'Marketing',
    description:
      'Hỗ trợ chiến dịch marketing, sáng tạo nội dung và quản lý mạng xã hội. Học chiến lược digital marketing trong môi trường FMCG quốc tế.',
    requirements: [
      'Sinh viên năm 3-4 ngành Marketing, Truyền thông, Kinh doanh hoặc liên quan',
      'Kỹ năng viết và giao tiếp tốt',
      'Quen thuộc các nền tảng mạng xã hội',
      'Sáng tạo, chú ý chi tiết',
      'Kiến thức cơ bản về digital marketing',
    ],
    preferred_skills: ['Content Creation', 'Social Media', 'Digital Marketing', 'Copywriting', 'Canva', 'Google Analytics', 'SEO', 'Communication', 'Creativity', 'Data Analysis'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_014',
    posted_at: daysAgo(4),
    remote: false,
  },
  {
    title: 'Digital Marketing Specialist',
    company: 'Coca-Cola Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Entry',
    field: 'Marketing',
    description:
      'Triển khai chiến dịch digital marketing đa kênh, tối ưu hiệu quả quảng cáo và phân tích dữ liệu chiến dịch. Làm việc với agency và đội nội bộ.',
    requirements: [
      'Tốt nghiệp đại học ngành Marketing, Truyền thông hoặc liên quan',
      'Kinh nghiệm 1+ năm digital marketing',
      'Thành thạo Google Ads, Facebook Ads',
      'Kiến thức SEO/SEM',
      'Kỹ năng phân tích dữ liệu',
    ],
    preferred_skills: ['Google Ads', 'Facebook Ads', 'SEO', 'Google Analytics', 'Content Marketing', 'Email Marketing', 'Social Media', 'Copywriting', 'Data Analysis', 'Canva'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_015',
    posted_at: daysAgo(6),
    remote: false,
  },
  {
    title: 'Product Intern',
    company: 'Lazada Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'hybrid',
    experience_level: 'Intern',
    field: 'Product',
    description:
      'Hỗ trợ đội product trong nghiên cứu người dùng, lên kế hoạch tính năng và phân tích sản phẩm. Học toàn bộ vòng đời phát triển sản phẩm trong nền tảng e-commerce.',
    requirements: [
      'Sinh viên năm 3-4 ngành Kinh doanh, Khoa học máy tính, Design hoặc liên quan',
      'Kỹ năng phân tích và giải quyết vấn đề',
      'Hiểu biết nguyên tắc trải nghiệm người dùng',
      'Kỹ năng giao tiếp và cộng tác tốt',
      'Quen thuộc khái niệm product management',
    ],
    preferred_skills: ['User Research', 'Data Analysis', 'Wireframing', 'Communication', 'Problem Solving', 'SQL', 'A/B Testing', 'Product Strategy', 'Figma', 'Agile'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_016',
    posted_at: daysAgo(8),
    remote: false,
  },
  {
    title: 'Product Manager',
    company: 'VNG Corporation',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Mid',
    field: 'Product',
    description:
      'Định hướng và phát triển sản phẩm số từ ý tưởng đến ra mắt. Làm việc chặt chẽ với engineering, design và business để tối ưu trải nghiệm người dùng.',
    requirements: [
      'Tốt nghiệp đại học ngành Kinh doanh, Khoa học máy tính hoặc liên quan',
      'Kinh nghiệm 3+ năm product management',
      'Kỹ năng phân tích dữ liệu mạnh',
      'Kinh nghiệm làm việc với Agile/Scrum',
      'Kỹ năng giao tiếp và lãnh đạo',
    ],
    preferred_skills: ['Product Strategy', 'Data Analysis', 'SQL', 'A/B Testing', 'User Research', 'Agile', 'Roadmapping', 'Wireframing', 'Stakeholder Management', 'Google Analytics'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_017',
    posted_at: daysAgo(3),
    remote: false,
  },
  {
    title: 'Business Development Executive',
    company: 'Vingroup',
    location: 'Hà Nội',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Entry',
    field: 'Business Development',
    description:
      "Hỗ trợ đội phát triển kinh doanh trong nghiên cứu thị trường, phân tích đối tác và lập kế hoạch chiến lược trong hệ sinh thái Vingroup.",
    requirements: [
      'Tốt nghiệp đại học ngành Kinh doanh, Kinh tế, Quản trị hoặc liên quan',
      'Kỹ năng nghiên cứu và phân tích mạnh',
      'Kỹ năng giao tiếp và thuyết trình xuất sắc',
      'Khả năng làm việc độc lập và theo nhóm',
      'Quan tâm chiến lược kinh doanh và phân tích thị trường',
    ],
    preferred_skills: ['Market Research', 'Communication', 'Presentation', 'Excel', 'PowerPoint', 'Negotiation', 'Business Strategy', 'Data Analysis', 'Project Management'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_018',
    posted_at: daysAgo(11),
    remote: false,
  },
  {
    title: 'Sales Executive',
    company: 'Masan Group',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Entry',
    field: 'Sales',
    description:
      'Phát triển và duy trì quan hệ khách hàng, đạt mục tiêu doanh số trong ngành hàng tiêu dùng. Làm việc với đội sales và marketing để mở rộng thị trường.',
    requirements: [
      'Tốt nghiệp đại học ngành Kinh doanh, Kinh tế hoặc liên quan',
      'Kỹ năng giao tiếp và thuyết phục tốt',
      'Khả năng làm việc dưới áp lực',
      'Có phương tiện di chuyển',
      'Kinh nghiệm sales là lợi thế',
    ],
    preferred_skills: ['Sales', 'Communication', 'Negotiation', 'Customer Relationship Management', 'Excel', 'Presentation', 'Market Research', 'Problem Solving', 'CRM Software'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_019',
    posted_at: daysAgo(7),
    remote: false,
  },
  {
    title: 'Human Resources Intern',
    company: 'P&G Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Human Resources',
    description:
      'Hỗ trợ đội nhân sự trong tuyển dụng, đào tạo và phúc lợi nhân viên. Học quy trình HR chuẩn quốc tế trong tập đoàn FMCG toàn cầu.',
    requirements: [
      'Sinh viên năm 3-4 ngành Quản trị nhân lực, Tâm lý học, Kinh doanh hoặc liên quan',
      'Kỹ năng giao tiếp và tổ chức tốt',
      'Thành thạo Excel, Word',
      'Chú ý chi tiết, bảo mật',
      'Tiếng Anh khá',
    ],
    preferred_skills: ['Communication', 'Excel', 'Recruitment', 'Employee Relations', 'Organizational Skills', 'PowerPoint', 'Time Management', 'HRIS', 'Onboarding', 'Data Analysis'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_020',
    posted_at: daysAgo(13),
    remote: false,
  },
  {
    title: 'Operations Specialist',
    company: 'Shopee Vietnam',
    location: 'TP. Hồ Chí Minh',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'Operations',
    description:
      'Quản lý và tối ưu quy trình vận hành nền tảng e-commerce. Phối hợp với đội warehouse, logistics và customer service để đảm bảo trải nghiệm người dùng.',
    requirements: [
      'Tốt nghiệp đại học ngành Quản trị, Kinh doanh, Kỹ thuật hoặc liên quan',
      'Kỹ năng phân tích dữ liệu',
      'Thành thạo Excel',
      'Kỹ năng tổ chức và quản lý thời gian',
      'Khả năng làm việc đa nhiệm',
    ],
    preferred_skills: ['Excel', 'Data Analysis', 'Process Improvement', 'Project Management', 'Communication', 'SQL', 'Power BI', 'Problem Solving', 'Logistics', 'Operations Management'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_021',
    posted_at: daysAgo(5),
    remote: false,
  },
  {
    title: 'Supply Chain Analyst',
    company: 'Nestlé Vietnam',
    location: 'Bình Dương',
    job_type: 'Full-time',
    work_arrangement: 'onsite',
    experience_level: 'Junior',
    field: 'Supply Chain',
    description:
      'Phân tích và tối ưu chuỗi cung ứng từ nhà máy đến điểm bán. Làm việc với dự báo nhu cầu, quản lý tồn kho và lập kế hoạch vận chuyển.',
    requirements: [
      'Tốt nghiệp đại học ngành Quản trị, Kỹ thuật, Kinh tế hoặc liên quan',
      'Kỹ năng phân tích dữ liệu mạnh',
      'Thành thạo Excel',
      'Kiến thức chuỗi cung ứng là lợi thế',
      'Kỹ năng giải quyết vấn đề',
    ],
    preferred_skills: ['Excel', 'Data Analysis', 'Supply Chain Management', 'Inventory Management', 'Forecasting', 'SQL', 'Power BI', 'Logistics', 'SAP', 'Statistics'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_022',
    posted_at: daysAgo(9),
    remote: false,
  },
  {
    title: 'Research Assistant',
    company: 'VinAI Research',
    location: 'Hà Nội',
    job_type: 'Part-time',
    work_arrangement: 'remote',
    experience_level: 'Intern',
    field: 'Research / AI',
    description:
      'Hỗ trợ nghiên cứu AI/ML trong các dự án computer vision và NLP. Cộng tác với nghiên cứu sinh PhD, cơ hội đồng tác giả công bố bài báo khoa học.',
    requirements: [
      'Sinh viên năm 3-4 ngành Khoa học máy tính, Toán học, Vật lý hoặc liên quan',
      'Kỹ năng lập trình Python mạnh',
      'Hiểu biết machine learning và deep learning',
      'Quen thuộc PyTorch hoặc TensorFlow',
      'Quan tâm nghiên cứu học thuật và công bố',
    ],
    preferred_skills: ['Python', 'PyTorch', 'TensorFlow', 'Machine Learning', 'Deep Learning', 'Computer Vision', 'NLP', 'Mathematics', 'Research', 'Paper Writing'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_023',
    posted_at: daysAgo(15),
    remote: true,
  },
  {
    title: 'AI / Machine Learning Intern',
    company: 'FPT AI',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'hybrid',
    experience_level: 'Intern',
    field: 'Data / AI',
    description:
      'Tham gia xây dựng và triển khai mô hình AI cho sản phẩm thực tế. Học quy trình MLOps, từ huấn luyện mô hình đến triển khai production.',
    requirements: [
      'Sinh viên năm 3-4 ngành Khoa học máy tính, Toán học hoặc liên quan',
      'Lập trình Python thành thạo',
      'Hiểu biết machine learning, deep learning',
      'Quen thuộc PyTorch/TensorFlow',
      'Ham học hỏi, tư duy nghiên cứu',
    ],
    preferred_skills: ['Python', 'PyTorch', 'TensorFlow', 'Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'MLOps', 'Docker', 'SQL'],
    application_url: null,
    external_url: null,
    source: 'seed',
    source_job_id: 'seed_024',
    posted_at: daysAgo(6),
    remote: false,
  },
  {
    title: 'Economics / Research Intern',
    company: 'Ngân hàng Nhà nước Việt Nam',
    location: 'Hà Nội',
    job_type: 'Internship',
    work_arrangement: 'onsite',
    experience_level: 'Intern',
    field: 'Research / Economics',
    description:
      'Hỗ trợ nghiên cứu chính sách tiền tệ, phân tích dữ liệu kinh tế vĩ mô và lập báo cáo định kỳ. Tiếp xúc thực tế với nghiên cứu chính sách kinh tế quốc gia.',
    requirements: [
      'Sinh viên năm 3-4 ngành Kinh tế học, Tài chính, Thống kê hoặc liên quan',
      'Kỹ năng phân tích kinh tế vững',
      'Thành thạo Excel, EViews hoặc R',
      'Kỹ năng viết và nghiên cứu tốt',
      'Chú ý chi tiết, chính xác',
    ],
    preferred_skills: ['Economics', 'Data Analysis', 'Excel', 'EViews', 'R', 'Statistics', 'Research', 'Report Writing', 'Macroeconomics', 'PowerPoint'],
    application_url: null,
    source: 'seed',
    source_job_id: 'seed_025',
    posted_at: daysAgo(10),
    remote: false,
  },
];